apiVersion: v1
kind: Service
metadata:
  name: ntp-server-service
  namespace: kube-ntp
spec:
  selector:
    app: ntp-server
  ports:
  - protocol: UDP
    port: 123
    targetPort: 123
  type: LoadBalancer
